### ISSUE TITLE
Creation of Analysis Request through JSON API is not supported. Request aborted.

### ISSUE THREAD

**Issue by min2great** [senaite/senaite.jsonapi#31]
When a request for the creation of AR is submitted through Senaite JSON API, it fails with the following message:

Creation of Analysis Request through JSON API is not supported. Request aborted.

The version of Senaite LIMS is 1.3.1.

**Comment by ramonski** [comment]
Developer note, because this is confusing:

We have `senaite.jsonapi` (this repository), which was initially planned as successor for the [internal JSON API](https://github.com/senaite/senaite.core/tree/master/bika/lims/jsonapi) that ships currently with `senaite.core`.

The Sample creation does currently *not work*  with the [internal JSON API](https://github.com/senaite/senaite.core/tree/master/bika/lims/jsonapi) only, but should work with `senaite.jsonapi`.

Hence, this issue needs to be fixed here: https://github.com/senaite/senaite.core/blob/master/bika/lims/jsonapi/create.py#L168

**Comment by eagle-hub** [comment]
hi @ramonski 

I am using Senaite JSON API 1.2.2
When I send a request to create AnalysisRequest it returns with ""No target UID/PATH information found"

I looked into ALLOWED_PORTAL_TYPES_TO_CREATE list and found that AnalysisRequest is listed but not working!

Any suggestions?

**Comment by xispa** [comment]
https://github.com/senaite/senaite.jsonapi/pull/32
